// Mock data for development
import { Booking, Customer, Service, Review } from "./types"

export const mockBookings: Booking[] = [
  {
    id: "1",
    serviceId: "s1",
    serviceName: "Basic Wash",
    customerId: "c1",
    customerName: "김민수",
    customerPhone: "010-1234-5678",
    petId: "p1",
    petName: "Max",
    petBreed: "Golden Retriever",
    date: "2026-02-07",
    startTime: "09:00",
    endTime: "10:00",
    duration: 60,
    price: 35000,
    status: "confirmed",
    paymentStatus: "paid",
    createdAt: "2026-02-05T10:00:00Z",
    updatedAt: "2026-02-05T10:00:00Z",
  },
  {
    id: "2",
    serviceId: "s2",
    serviceName: "Full Grooming",
    customerId: "c2",
    customerName: "이지은",
    customerPhone: "010-9876-5432",
    petId: "p2",
    petName: "Luna",
    petBreed: "Poodle",
    date: "2026-02-07",
    startTime: "10:30",
    endTime: "12:00",
    duration: 90,
    price: 65000,
    status: "confirmed",
    paymentStatus: "paid",
    specialInstructions: "민감한 발 (조심히 다루기)",
    createdAt: "2026-02-04T14:00:00Z",
    updatedAt: "2026-02-04T14:00:00Z",
  },
  {
    id: "3",
    serviceId: "s3",
    serviceName: "Nail Trim",
    customerId: "c3",
    customerName: "박준호",
    customerPhone: "010-5555-8888",
    petId: "p3",
    petName: "Charlie",
    petBreed: "Beagle",
    date: "2026-02-07",
    startTime: "13:00",
    endTime: "14:00",
    duration: 60,
    price: 20000,
    status: "pending",
    paymentStatus: "unpaid",
    createdAt: "2026-02-07T09:00:00Z",
    updatedAt: "2026-02-07T09:00:00Z",
  },
  {
    id: "4",
    serviceId: "s4",
    serviceName: "Spa Package",
    customerId: "c4",
    customerName: "정수진",
    customerPhone: "010-7777-1234",
    petId: "p4",
    petName: "Bella",
    petBreed: "Shih Tzu",
    date: "2026-02-07",
    startTime: "14:30",
    endTime: "16:00",
    duration: 180,
    price: 95000,
    status: "confirmed",
    paymentStatus: "paid",
    notes: "VIP 고객 (10회 이용)",
    createdAt: "2026-02-06T16:00:00Z",
    updatedAt: "2026-02-06T16:00:00Z",
  },
]

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    name: "김민수",
    phone: "010-1234-5678",
    email: "kim@email.com",
    joinedDate: "2024-06-15",
    totalVisits: 24,
    totalSpent: 1850000,
    lastVisit: "2026-02-03",
    status: "vip",
    loyaltyTier: "platinum",
    notificationPreferences: {
      sms: true,
      email: true,
      promotions: true,
    },
  },
  {
    id: "c2",
    name: "이지은",
    phone: "010-9876-5432",
    email: "lee@email.com",
    joinedDate: "2025-08-20",
    totalVisits: 8,
    totalSpent: 520000,
    lastVisit: "2026-02-07",
    status: "regular",
    loyaltyTier: "silver",
    notificationPreferences: {
      sms: true,
      email: true,
      promotions: false,
    },
    notes: "Luna는 발을 만지면 예민함",
  },
  {
    id: "c3",
    name: "박준호",
    phone: "010-5555-8888",
    email: "park@email.com",
    joinedDate: "2026-01-10",
    totalVisits: 3,
    totalSpent: 105000,
    lastVisit: "2026-01-20",
    status: "new",
    loyaltyTier: "bronze",
    notificationPreferences: {
      sms: true,
      email: false,
      promotions: false,
    },
  },
]

export const mockServices: Service[] = [
  {
    id: "s1",
    name: "Basic Wash",
    category: "grooming",
    duration: 60,
    price: 35000,
    description: "기본 목욕 서비스 (샴푸, 린스, 드라이)",
    popularity: 5,
    bookingsThisMonth: 48,
    revenueThisMonth: 1680000,
    isActive: true,
  },
  {
    id: "s2",
    name: "Full Grooming",
    category: "grooming",
    duration: 120,
    price: 65000,
    description: "전체 미용 (목욕, 스타일링, 발톱, 귀 청소)",
    popularity: 4,
    bookingsThisMonth: 35,
    revenueThisMonth: 2275000,
    isActive: true,
  },
  {
    id: "s3",
    name: "Nail Trim",
    category: "grooming",
    duration: 30,
    price: 20000,
    description: "발톱 정리",
    popularity: 3,
    bookingsThisMonth: 22,
    revenueThisMonth: 440000,
    isActive: true,
  },
  {
    id: "s4",
    name: "Spa Package",
    category: "grooming",
    duration: 180,
    price: 95000,
    description: "프리미엄 스파 패키지 (아로마, 마사지, 전체 미용)",
    popularity: 3,
    bookingsThisMonth: 18,
    revenueThisMonth: 1710000,
    isActive: true,
  },
]

export const mockReviews: Review[] = [
  {
    id: "r1",
    customerId: "c1",
    customerName: "김민수",
    bookingId: "1",
    serviceName: "Full Grooming",
    petName: "Max",
    rating: 5,
    comment: "Max가 너무 예쁘게 변신했어요! 털도 부드럽고 향기도 좋네요. 항상 친절하게 대해주셔서 감사합니다. 다음에 또 올게요!",
    date: "2026-02-06",
    reply: {
      text: "감사합니다, 김민수님! Max를 항상 잘 돌봐주셔서 감사해요. 다음 방문도 기대하겠습니다! 🐕",
      date: "2026-02-06",
      author: "Sarah",
    },
    isPublic: true,
  },
  {
    id: "r2",
    customerId: "c2",
    customerName: "이지은",
    bookingId: "2",
    serviceName: "Basic Wash",
    petName: "Luna",
    rating: 4,
    comment: "서비스는 좋았는데 조금 오래 기다렸어요. 그래도 Luna는 깨끗해졌습니다!",
    date: "2026-02-05",
    isPublic: true,
  },
  {
    id: "r3",
    customerId: "c3",
    customerName: "박준호",
    bookingId: "3",
    serviceName: "Training Session",
    petName: "Charlie",
    rating: 5,
    comment: "Charlie가 이제 '앉아'와 '기다려'를 잘 따라해요! 훈련사님이 인내심 있게 잘 가르쳐주셨습니다. 추천합니다!",
    date: "2026-02-04",
    reply: {
      text: "Charlie의 발전이 기뻐요! 계속해서 연습하면 더 좋아질 거예요.",
      date: "2026-02-04",
      author: "Sarah",
    },
    isPublic: true,
  },
]
